apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: etherealpods.sunday.com
spec:
  group: sunday.com
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                ttl:
                  type: integer
            status:
              type: object
              properties:
                resurrections:
                  type: integer
      additionalPrinterColumns:
      - name: Restarts
        type: integer
        jsonPath: .status.resurrections
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: etherealpods
    singular: etherealpod
    kind: EtherealPod
    shortNames:
    - ep